### ISSUE TITLE
[Problem Executing the Project] (OS) One liner description of the issue.

### ISSUE THREAD

**Issue by sakthidhar** [HaiderAbasi/ROS2-Path-Planning-and-Maze-Solving#9]
### Prerequisites

* [ ] Are you running the latest version (Repo)?
* [ ] Did you follow the How_to_Run_the_project guide in Section 1 (Lec 1 & 2)?
* [ ] Did you check Issues on Github for related queries?
* [ ] Did you try restarting the PC and re-doing the steps in Section 1 (Lec 1 & 2)?
* [ ] Is the problem persistent?

### Description

Unable to run the project(lecture 2)

### Steps to Reproduce

1. ros2 launch maze_bot maze_2_robot_camera.launch.py
2. ros2 run maze_bot maze_solver
3. [and so on...]

**Expected behavior:** Wanted to run complete project as stated in Lecture 2 

**Actual behavior:** Getting error, there is no sat_view or robot movement

**Screenshots**
![Screenshot from 2022-11-03 07-59-10](https://user-images.githubusercontent.com/112263988/199778800-41980b5c-245e-4f6c-b9c0-30184174b303.png)

**Environment (please complete the following information):**
 - OS: ubuntu (using in VM)
 - OS-Version 20.04 LTS
 - Python-Version [e.g. 3.6] - compatable with the code
 - OpenCV-Version [e.g. 4.2]

**Hardware**
- Laptop 
  - Make-Model (If Any) [e.g. MSI - GF65]
- GPU [e.g. Nvidia RTX 3060]

**Additional context** (Optional)

**Comment by HaiderAbasi** [comment]
1) Is your gazebo running When you run this? Paste screenshot
2) Try displaying the image before this error
( Add below lines before line 90 in extractbg() in bot_localization.py )

cv2.imshow("img",frame)
cv2.waitKey(0)


> Display the image that you get after running the project again after
adding the code

**Comment by sakthidhar** [comment]
![Screenshot from 2022-11-03 10-25-48](https://user-images.githubusercontent.com/112263988/199792603-1589434d-88e7-49b4-9a46-422e1931911c.png)
![Screenshot from 2022-11-03 10-26-11](https://user-images.githubusercontent.com/112263988/199792617-a6423e16-cdb4-48e8-903a-05437bd098bb.png)

**Comment by sakthidhar** [comment]
![Screenshot from 2022-11-03 10-39-24](https://user-images.githubusercontent.com/112263988/199794955-bbb579d8-4989-4259-aff2-51d1934db055.png)

**Comment by sakthidhar** [comment]
![Screenshot from 2022-11-03 10-42-49](https://user-images.githubusercontent.com/112263988/199795693-dd7b227a-4ca2-4a57-8354-74e97d073f69.png)
Sir, this is without the commands {cv.imshow) you mentioned, I am getting this error now apart from the error which i posted at first

**Comment by sakthidhar** [comment]
![Screenshot from 2022-11-03 10-47-28](https://user-images.githubusercontent.com/112263988/199798220-3bd61d14-7f14-4e52-9dfa-3543338202ec.png)
![Screenshot from 2022-11-03 10-47-31](https://user-images.githubusercontent.com/112263988/199798231-88edede8-5837-44ea-b350-2f9d63e69461.png)
![Screenshot from 2022-11-03 10-47-35](https://user-images.githubusercontent.com/112263988/199798240-25e5b747-0779-4cbb-9e4c-9f88433ed69f.png)
![Screenshot from 2022-11-03 10-47-53](https://user-images.githubusercontent.com/112263988/199798244-ac55864e-1350-45be-bc0c-7304d6345270.png)
![Screenshot from 2022-11-03 10-53-44](https://user-images.githubusercontent.com/112263988/199798253-0dbcf416-9912-4a68-bacd-5342e05cfb82.png)
![Screenshot from 2022-11-03 10-53-47](https://user-images.githubusercontent.com/112263988/199798260-a57004a5-7f74-4def-90df-9911d1054298.png)
![Screenshot from 2022-11-03 10-53-51](https://user-images.githubusercontent.com/112263988/199798282-b95e7d4a-0f17-427d-a49a-b129c2c270dd.png)
these are what i got, that means its working , isnt it?

**Comment by HaiderAbasi** [comment]
Ok that's good that you moved forward...

Now the error is different. This is related to rois_mask not being correct 

Can you show me what you get there. Try the same imshow code before line 105 for rois_mask
Show me the output.

cv2.imshow("rois_mask",rois_mask)
cv2.waitKey(0)

**Comment by HaiderAbasi** [comment]
Yup Perfect, 
The last error was because the car had moved inside the maze and was stuck at wall.
The algorithm was considering the car to be separate from the maze. But as it was besides the wall it was considered part of the maze and that's what caused the error (cannot find the car.)
Framr_carremoved referenced before assignment.

I am closing this if your issue is resolved ☺️

**Comment by sakthidhar** [comment]
> Yup Perfect, The last error was because the car had moved inside the maze and was stuck at wall. The algorithm was considering the car to be separate from the maze. But as it was besides the wall it was considered part of the maze and that's what caused the error (cannot find the car.) Framr_carremoved referenced before assignment.
> 
> I am closing this if your issue is resolved relaxed

Thank you Sir for your time
